org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx1024M"
android.enableJetifier=true
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.enableR8.fullMode=false
org.gradle.configuration-cache=false
org.gradle.configureondemand=false
org.gradle.parallel=true